// File vhdl/fpnormalize.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-reg.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.FPnormalize.FPnormalize
//
// Created:
//          by - Guillermo
//          at - ITESM, 10:51:00 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPnormalizeAdd #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    input wire [SIGWIDTH + 4:0] SIG_in,
    input wire [EWIDTH - 1:0] EXP_in,
    output [SIGWIDTH + 3:0] SIG_out,
    output [EWIDTH - 1:0] EXP_out);

localparam SHIFT_BITS = $clog2(SIGWIDTH + 5);

wire [SHIFT_BITS - 1:0] shift_factor;
wire shift_dir;
// verilator lint_off UNUSEDSIGNAL
logic [SIGWIDTH + 4:0] SIG_intermediate;
// verilator lint_on UNUSEDSIGNAL

logic [SHIFT_BITS - 1:0] leading_bit_pos;
int i;

  assign shift_dir = leading_bit_pos > (SIGWIDTH[SHIFT_BITS - 1:0] + 3);
  assign shift_factor = (SIG_in == 0 && EXP_in == 0) ? 0 :
      (shift_dir == 1'b1 ? (leading_bit_pos - (SIGWIDTH[SHIFT_BITS - 1:0] + 3)) :
      (SIGWIDTH[SHIFT_BITS - 1:0] + 3 - leading_bit_pos));

  always @(*) begin
      leading_bit_pos = 0;
      for (i = 0; i <= SIGWIDTH + 4; i = i + 1) begin
          if (SIG_in[i] == 1'b1)
            leading_bit_pos = (SHIFT_BITS)'(i);
      end
  end

  always @(*) begin
    SIG_intermediate = shift_dir == 1'b1 ? (SIG_in >> shift_factor) : (SIG_in << shift_factor);
  end

  assign EXP_out = shift_dir == 1'b1 ? (EXP_in + {{(EWIDTH - SHIFT_BITS){1'b0}}, shift_factor}) : (EXP_in - {{(EWIDTH - SHIFT_BITS){1'b0}}, shift_factor});
  assign SIG_out = SIG_intermediate[SIGWIDTH + 3:0];

endmodule
