// File vhdl/fpnormalize.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-reg.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.FPnormalize.FPnormalize
//
// Created:
//          by - Guillermo
//          at - ITESM, 10:51:00 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPnormalizeMul #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    input [2 * (SIGWIDTH + 1) - 1:0] SIG_in,
    input [EWIDTH - 1:0] EXP_in,
    output [SIGWIDTH + 3:0] SIG_out,
    output [EWIDTH - 1:0] EXP_out);

localparam SIGWIDTH_EXT = 2 * (SIGWIDTH + 1);
localparam SHIFT_BITS = $clog2(SIGWIDTH_EXT);

wire [SHIFT_BITS - 1:0] shift_factor;
// verilator lint_off UNUSEDSIGNAL
reg [SIGWIDTH_EXT - 1:0] SIG_intermediate;
// verilator lint_on UNUSEDSIGNAL

  assign shift_factor = (SIG_in[SIGWIDTH_EXT - 1] == 1'b1 ? (SIGWIDTH_EXT[SHIFT_BITS - 1:0] - 1) : (SIGWIDTH_EXT[SHIFT_BITS - 1:0] - 2)) - (SIGWIDTH[SHIFT_BITS - 1:0] + 3);

  always @(*) begin
    SIG_intermediate = SIG_in >> shift_factor;
  end

  assign EXP_out = EXP_in + {{(EWIDTH - 1){1'b0}}, (SIG_in[SIGWIDTH_EXT - 1] == 1 ? 1'b1 : 1'b0)};
  assign SIG_out = SIG_intermediate[SIGWIDTH + 3:0];

endmodule
