// File vhdl/fpnormalize.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-logic.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.FPnormalize.FPnormalize
//
// Created:
//          by - Guillermo
//          at - ITESM, 10:51:00 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPnormalizeAdd #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    input logic [SIGWIDTH + 4:0] SIG_in,
    input logic [EWIDTH - 1:0] EXP_in,
    output [SIGWIDTH + 3:0] SIG_out,
    output logic [EWIDTH - 1:0] EXP_out);

// verilator lint_off UNUSEDSIGNAL
logic [SIGWIDTH + 4:0] SIG_intermediate;
logic [SIGWIDTH + 3:0] SIG_truncated;
// verilator lint_on UNUSEDSIGNAL

localparam LBPWIDTH = $clog2(SIGWIDTH+5);
logic [LBPWIDTH - 1:0] leading_zeros;
logic [LBPWIDTH - 1:0] leading_zeros_minus_one;
int i;

always_comb begin
    // Might want to steal someone else's more optimized code
    leading_zeros = 0;
    for (i = 0; i <= SIGWIDTH + 4; i++) begin
        if (SIG_in[SIGWIDTH + 4 - i] == 1'b1) begin
            leading_zeros = (LBPWIDTH)'(i);
            break;
        end
    end

    leading_zeros_minus_one = leading_zeros - (LBPWIDTH)'(1);

    if (leading_zeros > 1)
        if (EXP_in < {{EWIDTH-LBPWIDTH{1'b0}}, leading_zeros_minus_one}) EXP_out = 0;
        else EXP_out = EXP_in - {{EWIDTH-LBPWIDTH{1'b0}}, leading_zeros_minus_one};
        // EXP_out = EXP_in - {{EWIDTH-LBPWIDTH{1'b0}}, rshift};
    else begin
        if (SIG_in[SIGWIDTH + 4] == 1'b1)
            EXP_out = EXP_in + 1;
        else
            EXP_out = EXP_in;
    end
end

assign SIG_intermediate = EXP_in < {(EWIDTH-LBPWIDTH)'(0), leading_zeros} ? 0 : SIG_in << leading_zeros;
assign SIG_truncated = {SIG_intermediate[SIGWIDTH + 4:2], |SIG_intermediate[1:0]};


assign SIG_out = SIG_truncated;

endmodule
