// File vhdl/fppack.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-reg.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.PackFP.PackFP
//
// Created:
//          by - Guillermo
//          at - ITESM, 09:57:50 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPpack #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    input wire SIGN,
    input wire [EWIDTH - 1:0] EXP,
    // verilator lint_off UNUSEDSIGNAL
    input wire [SIGWIDTH:0] SIG,
    // verilator lint_on UNUSEDSIGNAL
    input wire isNaN,
    input wire isINF,
    input wire isZ,
    output logic [EWIDTH + SIGWIDTH:0] FP
    );

localparam WIDTH = 1 + EWIDTH + SIGWIDTH;

  always @(*) begin
    if((isNaN == 1'b1)) begin
      FP[WIDTH - 1] = SIGN;
      FP[WIDTH - 2:SIGWIDTH] = {EWIDTH{1'b1}};
      FP[SIGWIDTH - 1:0] = {3'b100,{(SIGWIDTH - 3){1'b0}}};
    end
    else if((isINF == 1'b1)) begin
      FP[WIDTH - 1] = SIGN;
      FP[WIDTH - 2:SIGWIDTH] = 8'hFF;
      FP[SIGWIDTH - 1:0] = {23{1'b0}};
    end
    else if((isZ == 1'b1)) begin
      FP[WIDTH - 1] = SIGN;
      FP[WIDTH - 2:SIGWIDTH] = 8'h00;
      FP[SIGWIDTH - 1:0] = {23{1'b0}};
    end
    else begin
      FP[WIDTH - 1] = SIGN;
      FP[WIDTH - 2:SIGWIDTH] = EXP;
      FP[SIGWIDTH - 1:0] = SIG[SIGWIDTH - 1:0];
    end
  end


endmodule
