// File vhdl/fpround.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-reg.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.FPround.FPround
//
// Created:
//          by - Guillermo
//          at - ITESM, 11:08:16 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPround #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    // verilator lint_off UNUSEDSIGNAL
    input wire [SIGWIDTH + 3:0] SIG_in,
    // verilator lint_on UNUSEDSIGNAL
    input wire [EWIDTH - 1:0] EXP_in,
    output [SIGWIDTH:0] SIG_out,
    output wire [EWIDTH - 1:0] EXP_out
);

logic [SIGWIDTH + 1:0] SIG_intermediate;
logic [SIGWIDTH:0] SIG_rounded;
logic [EWIDTH - 1:0] EXP_intermediate;

  always @(*) begin
    if((SIG_in[2] == 1'b1 && SIG_in[1] == 1'b1) || (SIG_in[3] == 1'b1 && SIG_in[2] == 1'b1 && SIG_in[1] == 1'b0)) begin
      SIG_intermediate = {1'b0, SIG_in[SIGWIDTH + 3:3]} + 1;
    end
    else begin
      SIG_intermediate = {1'b0, SIG_in[SIGWIDTH + 3:3]};
    end

    if (SIG_intermediate[SIGWIDTH + 1] == 1'b1) begin
        SIG_rounded = SIG_intermediate[SIGWIDTH + 1:1];
        EXP_intermediate = EXP_in + 1;
    end else begin
        SIG_rounded = SIG_intermediate[SIGWIDTH:0];
        EXP_intermediate = EXP_in;
    end
  end

  assign EXP_out = EXP_intermediate;
  assign SIG_out = SIG_rounded;

endmodule
