// File vhdl/fpunpack.vhd translated with vhd2vl 3.0 VHDL to Verilog RTL translator
// vhd2vl settings:
//  * Verilog Module Declaration Style: 2001

// vhd2vl is Free (libre) Software:
//   Copyright (C) 2001-2023 Vincenzo Liguori - Ocean Logic Pty Ltd
//     http://www.ocean-logic.com
//   Modifications Copyright (C) 2006 Mark Gonzales - PMC Sierra Inc
//   Modifications (C) 2010 Shankar Giri
//   Modifications Copyright (C) 2002-2023 Larry Doolittle
//     http://doolittle.icarus.com/~larry/vhd2vl/
//   Modifications (C) 2017 Rodrigo A. Melo
//
//   vhd2vl comes with ABSOLUTELY NO WARRANTY.  Always check the resulting
//   Verilog for correctness, ideally with a formal verification tool.
//
//   You are welcome to redistribute vhd2vl under certain conditions.
//   See the license (GPLv2) file included with the source for details.

// The result of translation follows.  Its copyright status should be
// considered unchanged from the original VHDL.

//
// VHDL Architecture HAVOC.UnpackFP.UnpackFP
//
// Created:
//          by - Guillermo
//          at - ITESM, 09:06:00 07/16/03
//
// Generated by Mentor Graphics' HDL Designer(TM) 2002.1b (Build 7)
//

module FPunpack #(
    parameter EWIDTH = 8,
    parameter SIGWIDTH = 23) (
    input logic [EWIDTH + SIGWIDTH:0] FP,
    output logic [SIGWIDTH:0] SIG,
    output logic [EWIDTH - 1:0] EXP,
    output logic SIGN,
    output logic isNaN,
    output logic isINF,
    output logic isZ
    );

localparam WIDTH = 1 + EWIDTH + SIGWIDTH;

logic [EWIDTH - 1:0] exp_int;
logic [SIGWIDTH - 1:0] sig_int;
logic expZ; logic expFF; logic sigZ;

assign exp_int = FP[WIDTH - 2:SIGWIDTH];
assign sig_int = FP[SIGWIDTH - 1:0];
assign SIGN = FP[WIDTH - 1];
assign EXP = exp_int;
assign SIG[SIGWIDTH - 1:0] = sig_int;
assign expZ = (exp_int == {EWIDTH{1'b0}}) ? 1'b1 : 1'b0;
assign expFF = (exp_int == {EWIDTH{1'b1}}) ? 1'b1 : 1'b0;
assign sigZ = (sig_int == {SIGWIDTH{1'b0}}) ? 1'b1 : 1'b0;
assign isNaN = expFF & ( ~sigZ);
assign isINF = expFF & sigZ;
assign isZ = expZ & sigZ;

// Restore hidden 1.ffff when not zero or denormal
assign SIG[SIGWIDTH] =  ~expZ;

endmodule
